language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit
  
branches:
  only:
    - master
