language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.example .env
  - mysql -u root -e 'CREATE SCHEMA IF NOT EXISTS homestead DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;'
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL ON homestead.* to homestead@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - composer self-update
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit
  
branches:
  only:
    - master
